name: notebooks-environment
channels:
  - conda-forge
dependencies:
  - python=3.6
  - contextily
  - geopandas
  - fuzzywuzzy
  - libpysal
  - matplotlib
  - numpy
  - osmnx
  - pandas
  - requests
  - rtree
  - scipy
  - segregation
  - six
  - pip
    - git+https://github.com/cenpy-devs/cenpy.git@master
